# Generated by Django 3.1.1 on 2020-09-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('name_author', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя автора')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Понравилось')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='entry', to='blog.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.rubric', verbose_name='Рубрика'),
        ),
    ]
