# Generated by Django 3.1.1 on 2020-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201017_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='default/750x300', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
