# Generated by Django 3.1.1 on 2020-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='default/750x300', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
