# Generated by Django 3.1.1 on 2020-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, default='default/750x300', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
