# Generated by Django 3.1.1 on 2020-10-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
