# Generated by Django 3.1.1 on 2020-10-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201017_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
